version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "9002:9002"
    command: python3 /opt/code/python-ismrmrd-server/main.py -v -H 0.0.0.0 -p 9002
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile
    network_mode: host
    volumes:
      - .:/tmp
    command: python3 /opt/code/python-ismrmrd-server/client.py -a localhost -p 9002 -c swig -o /tmp/out.h5 /data/mitral_ip.h5
    depends_on:
      - server